IF NOT EXISTS (SELECT LoginName FROM SYSLOGINS WHERE NAME = 'IIS APPPOOL\Auth')
BEGIN
	CREATE LOGIN [IIS APPPOOL\Auth] FROM WINDOWS WITH DEFAULT_DATABASE = [Auth], DEFAULT_LANGUAGE = [us_english]
END
GO

IF NOT EXISTS (SELECT [Name] FROM SYSUSERS WHERE [Name] = 'IIS APPPOOL\Auth')
BEGIN
	CREATE USER [IIS APPPOOL\Auth] FOR LOGIN [IIS APPPOOL\Auth] WITH DEFAULT_SCHEMA = dbo
END
GO

GRANT CONNECT TO [IIS APPPOOL\Auth]
GO

GRANT EXECUTE ON [dbo].[FindApiResourceByName] TO [IIS APPPOOL\Auth]
GRANT EXECUTE ON [dbo].[FindApiResourcesByScope] TO [IIS APPPOOL\Auth]
GRANT EXECUTE ON [dbo].[FindClientById] TO [IIS APPPOOL\Auth]
GRANT EXECUTE ON [dbo].[FindProviderById] TO [IIS APPPOOL\Auth]
GRANT EXECUTE ON [dbo].[FindUserByExternalProvider] TO [IIS APPPOOL\Auth]
GRANT EXECUTE ON [dbo].[FindUserByUsername] TO [IIS APPPOOL\Auth]
GRANT EXECUTE ON [dbo].[GetApiResources] TO [IIS APPPOOL\Auth]
GO
